POST http://localhost:5002/api/Blog
Content-Type: application/json
Accept: application/json
{
  "languageType": 0,
  "title": "string",
  "description": "string",
  "content": "string",
  "isPublic": true,
  "isOriginal": true,
  "catalogId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "tags": [
    "string"
  ]
}